config/routes.rb
Rails.application.routes.draw do
  get 'profiles/show'

  devise_for :users
  devise_scope :user do
    get 'register', to: 'devise/registrations#new', as: :register
    get 'login', to: 'devise/sessions#new', as: :login
    get 'logout', to: 'devise/sessions#destroy', as: :logout
  end

  resources :games
  get 'collection', to: 'games#index', as: :collection
  root to: 'games#index'

  get '/:id', to: 'profiles#show'

end

app/models/game.rb
class Game < ActiveRecord::Base
	belongs_to :user

	validates :name, presence: true,
					 length: { minimum: 2 }

	validates :user_id, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :profile_name, presence: true, 
                           uniqueness: true, 
                           format: {
                              with: /\A[a-zA-Z0-9_-]+\z/, 
                              message: "Must be formatted correctly"
                            }

  has_many :games
  has_many :user_friendships
  has_many :friends, through: :user_friendships

  def full_name
  	first_name + " " + last_name
  end

end

app/models/user_friendship.rb
class UserFriendship < ActiveRecord::Base
	belongs_to :user
	belongs_to :friend, class_name: 'User', foreign_key: 'friend_id'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters 
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:first_name, :last_name, :profile_name, :email, :password) } 
  end


end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_filter :authenticate_user!, only: [:new, :create, :edit, :update]
  before_action :set_game, only: [:show, :edit, :update, :destroy]

  # GET /games
  # GET /games.json
  def index
    @games = Game.all
  end

  # GET /games/1
  # GET /games/1.json
  def show
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  # POST /games.json
  def create
    @game = current_user.games.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    @game = current_user.games.find(params[:id])
    if params[:game].has_key?(:user_id)
      params[:game].delete(:user_id)
    end
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url, notice: 'Game was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.require(:game).permit(:user_id, :name)
    end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show
  	@user = User.find_by_profile_name(params[:id])
  	if @user 
  		@games = @user.games.all
  		render action: :show
  	else
  		render file: 'public/404', status: 404, formats: [:html]
  	end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def flash_class(type)
		case type
		when 'notice'
			"alert-success"
		when 'alert'
			"alert-danger"
		else ""
		end
	end

end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/games/_form.html.erb
<%= simple_form_for @game, html: {class: "form-horizontal" }, wrapper: :horizontal_form do |f| %>
  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% @game.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="col-xs-3">
    <%= f.input :name %>
  </div>
  <div class="form-group">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/games/edit.html.erb
<h1>Editing Game</h1>

<%= render 'form' %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<!-- <p id="notice"><%= notice %></p> -->

<div class="page-header">
  <h1>Your Game Shelf</h1>
</div>

<%= link_to "Add a game", new_game_path, class: "btn btn-success" %>

<% @games.each do |game| %>
<div class="game">
  <strong><%= game.user.full_name %></strong> | <%= game.name %>
  <div class="meta">
    <%= link_to time_ago_in_words(game.created_at) + " ago", game %>
    <span class="admin">
      <%= link_to "Edit game", edit_game_path(game) %> |
      <%= link_to "Remove from shelf", game, method: :delete, data: { confirm: "Are you sure you want to remove this game from your shelf?"} %>
    </span>
  </div> 
</div>
<% end %>

app/views/games/new.html.erb
<h1>New Game</h1>

<%= render 'form' %>

<%= link_to 'Back', games_path %>

app/views/games/show.html.erb
<p>
  <strong>User</strong>
  <%= @game.user.full_name %>
</p>

<p>
  <strong>Name</strong>
  <%= @game.name %>
</p>

<%= link_to 'Edit', edit_game_path(@game) %> |
<%= link_to 'Back', games_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bgln</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="navbar navbar-default navbar-fixed-top">
		<div class="container">
			<a class="navbar-brand" href="#">Boardgame Lending Network</a>
			<ul class="nav navbar-nav">
				<li><%= link_to "All Games", collection_path %></a></li>
			</ul>
			<ul class="nav navbar-nav navbar-right">
				<% if user_signed_in? %>
					<li><%= link_to current_user.full_name, edit_user_registration_path %></li>
					<li><%= link_to "Sign Out", logout_path %></li>
				<% else %>
					<li><%= link_to "Create an Account", register_path %></li>
					<li><%= link_to "Log in", login_path %></li>
				<% end %>
			</ul>
		</div>
	</div>
	<div class="container">
		<% flash.each do |type, message| %>
			<div class="alert <%= flash_class type %> alert-dismissable" role="alert">
				<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<%= message %>
			</div>
		<% end %>

		<%= yield %>
	</div>
</body>
</html>

app/views/profiles/show.html.erb
<div class="page-header">
	<h1><%= @user.full_name %></h1>
</div>

<% if @games %>
	<% @games.each do |game| %>
		<div class="well">
			<%= game.name %>
			<br />
			<%= link_to time_ago_in_words(game.created_at), game_path(game) %> ago
		</div>
	<% end %>
<% end %>